JARFILEPATH = `pwd`/target/hw3-PageRank-0.0.1-SNAPSHOT-jar-with-dependencies.jar
FILEPATH = `pwd`/*.bz2
OUTPUTPATH = `pwd`/output

default: 
	mvn install

local:
	java -jar $(JARFILEPATH) $(FILEPATH) $(OUTPUTPATH)